set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE STRING "")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE STRING "")

set(CMAKE_C_FLAGS_DEBUG_INIT "-Og -glldb")
set(CMAKE_CXX_FLAGS_INIT "-stdlib=libc++")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG -Og -glldb")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_FAST")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-lc++ -lc++abi")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-lc++ -lc++abi")
